# Generated by Django 3.0.8 on 2020-08-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdown', '0002_dropdownmodel_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownmodel',
            name='date_range',
            field=models.CharField(choices=[('Today', 'Today'), ('Yesterday', 'Yesterday'), ('Custom', 'Custom')], max_length=50),
        ),
    ]
